import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginButton from './LoginButton'
import LogoutButton from './LogoutButton'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
	let logInfo = await getServerSession(authOptions)
	// console.log(logInfo)
	return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">  
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link>
          <Link href="/write">글쓰기</Link>
				
					{
						// jsx안에서 if 문 사용 불가능, If문이 필요하면
						// 삼항 연산자를 가져다 써야함
						// 조건식 ? 조건식참일때실행코드 : 거짓일때실행할코드
						(logInfo) ? ( <>
							<LogoutButton /> 
							Welcome, { logInfo.user.name }
						</>) : (<LoginButton/>)
					}
      </div>  
        {children}
      </body>
    </html>
  )
}

